首先，执行try子句（在关键字try和关键字except之间的语句）
如果没有异常发生，忽略except子句，try子句执行后结束。
如果在执行try子句的过程中发生了异常，那么try子句余下的部分将被忽略。如果异常的类型和 except 之后的名称相符，那么对应的except子句将被执行。最后执行 try 语句之后的代码。
'''
如果一个异常没有与任何的except匹配，那么这个异常将会传递给上层的try中。[错]
如果 没有的话直接就报错了，不会传递上层执行
'''

一个except子句可以同时处理多个异常，
这些异常将被放在一个括号里成为一个元组，
例如: #用这种方式统一处理，但这样就没法定制化了
except (RuntimeError, TypeError, NameError):
        pass

也可以依次分开放
try except 语句还有一个可选的else子句，
如果使用这个子句，那么必须放在所有的except子句之后。
这个子句将在try子句没有发生任何异常的时候执行。例如:


以上例子不管 try 子句里面有没有发生异常，finally 子句都会执行。
